---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.9
  - name: centos-6.5
  - name: centos-7.0
  - name: fedora-20
  - name: fedora-21

suites:
- name: remi
  run_list:
  - recipe[yum-remi::remi]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true

- name: remi-php55
  run_list:
  - recipe[yum-remi::remi-php55]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
      remi-php55:
        enabled: true
        managed: true
  excludes: [ 
    'fedora-20',
    'fedora-21',
  ]

- name: remi-php56
  run_list:
  - recipe[yum-remi::remi-php56]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
      remi-php56:
        enabled: true
        managed: true
  excludes: [
    'fedora-21' 
  ]
