language: 
  - ruby
rvm:
  - 2.0.0
bundler_args: --without integration --without kitchen_vagrant --without kitchen_cloud
script:
  - bundle exec foodcritic .
  - bundle exec rspec -c -fd
  - bundle exec rubocop
